### ISSUE TITLE
Newer git version 2.21.0 available upstream

### ISSUE THREAD

**Issue by nkadel** [iuscommunity-pkg/git2u#11]
The latest upstream version is 2.21.0.

**Comment by nkadel** [comment]
Python3 is also supported upstream: it can be enabled by building python modules for it, and using "python3_pkgversion" settings built into pythn34 or python36 from EPEL and, possibly, from iusrelease.

I publish some updated build tools at https://github.com/nkadel/git2u-srpm/, especially the .spec file.

**Comment by carlwgeorge** [comment]
There is some backstory here you should be aware of.

https://github.com/iuscommunity-pkg/git2u/issues/10 (especially https://github.com/iuscommunity-pkg/git2u/issues/10#issuecomment-428360542)

TLDR: git2u is going to stay on 2.16.x, and at some point I'll create a git221 (or whatever maintained version is targeted) package as a newer alternative.  The end result of the above issue was that I asked for someone to create a git218 [wishlist request](https://github.com/iusrepo/wishlist), but that never happened, so it kinda fell off my radar.

Please open [wishlist request](https://github.com/iusrepo/wishlist) request for git221 and I'll see if I can deliver it.

**Comment by carlwgeorge** [comment]
I've created new git222 packages.  If you are interested in helping test them please share your feedback in [iusrepo/wishlist#241](https://github.com/iusrepo/wishlist/issues/241).

**Comment by benyaminl** [comment]
> I've created new git222 packages. If you are interested in helping test them please share your feedback in [iusrepo/wishlist#241](https://github.com/iusrepo/wishlist/issues/241).

Hello I'm new on ius repo. I want the git222 pacakge, is there anyway to install it? Thanks

**Comment by carlwgeorge** [comment]
@benyaminl Have you subscribed to the repository yet?  git222 is still in the testing repository, but once you've added the ius-release package (https://ius.io/GettingStarted/) you can run this command.

```
yum --enablerepo ius-testing install git222-core
```

I'll be promoting git222 to stable soon, and then the `--enablerepo ius-testing` flag will no longer be necessary.

If you have further questions, join our IRC channel, `#ius` on [freenode](https://freenode.net).
