### ISSUE TITLE
git2u-gitk 2.7.0 fails to run on CentOS 6

### ISSUE THREAD

**Issue by tlusk** [iuscommunity-pkg/git2u#3]
```
$ gitk
Error in startup script: unknown color name "lime"
    (processing "-fore" option)
    invoked from within
"$ctext tag conf m2 -fore [lindex $mergecolors 2]"
    (procedure "makewindow" line 347)
    invoked from within
"makewindow"
    (file "/usr/bin/gitk" line 12434)
```

Appears to be the version of Tcl installed in CentOS 6 doesn't understand the color lime:
http://stackoverflow.com/questions/34637896/gitk-will-not-start-on-mac-unknown-color-name-lime

**Comment by b-harper** [comment]
Hello @tlusk,

Thanks for taking the time to submit this issue.  I am able to confirm this issue and get the same error message.  The stock version of gitk does not have this issue.

The fix in the stackoverflow article does work.  I typically do not recommend those types manually changes, but could tie you over until we get a fix into the repositories.

**Comment by tlusk** [comment]
Thanks @b-harper, I can also confirm the stackoverflow workaround does work.  Just wanted to give you guys a heads up so it could be fixed for others than ran into the issue.

**Comment by b-harper** [comment]
oh... man.  It is a Friday.  Looks like this got patched in 2.7.1 which is currently in the testing repositories.

**Comment by b-harper** [comment]
Looking closer, 2.7.1 did not correct this issue.  Version 2.7.2 just got released and I will roll the fix into that release.

**Comment by tlusk** [comment]
Glad to hear it.  Seems like such silly behavior for Tcl to completely error out if it finds a color it doesn't know instead of just printing a warning and defaulting to white or something.

**Comment by b-harper** [comment]
Updated packages have been built and will hit the testing repositories after tonight's automation run.

**Comment by carlwgeorge** [comment]
This fix has made it to the stable repos.
